CUDNN:
  BENCHMARK: true
  DETERMINISTIC: false
  ENABLED: true
BACKBONE_MODEL: 'pose_higher_hrnet' #'pose_resnet' 
MODEL: 'hrnet_adabins'
DATA_DIR: ''
GPUS:  '0,1'
OUTPUT_DIR: 'result/fusing_tr_samedim' 
LOG_DIR: 'log'
WORKERS: 16
PRINT_FREQ: 5
BINS: 256

DATASET:
  MIN_DEPTH: 0.01
  MAX_DEPTH: 8.0
  MAX_PEOPLE_NUM: 10
  TRAIN_VIEW_SET:
    - 1
    - 2
    - 3
    - 9
    - 10
  TEST_VIEW_SET:
    - 4
    - 5
    - 6
    - 7
    - 8
  COLOR_RGB: True
  TRAIN_DATASET: 'panoptic_depth'
  TEST_DATASET: 'panoptic_depth'
  DATA_FORMAT: jpg
  DATA_AUGMENTATION: False
  FLIP: False
  ROOT: '/Extra/panzhiyu/CMU_kinect_data/'  # 'data/panoptic/'
  KP_ROOT: '/Extra/panzhiyu/CMU_data/'
  ROT_FACTOR: 45
  SCALE_FACTOR: 0.35
  TEST_SUBSET: 'validation'
  TRAIN_SUBSET: 'train'
  ROOTIDX: # in coco standard
    - 11
    - 12
  CAMERA_NUM: 5 #5 
  IMAGE_SIZE:
    - 1920
    - 1080
NETWORK: # for the 
  FEATURE: True 
  PRETRAINED_BACKBONE: '/home/panzhiyu/project/3d_pose/voxelpose-pytorch/models_bak/model_best.pth.tar'    #'models/pose_higher_hrnet_w32_512.pth' #pose_higher_hrnet_w32_512.pth 'models/pose_resnet50_panoptic.pth.tar' # change this 
  PRETRAINED:  ''  # 'models/pytorch/imagenet/resnet50-19c8e357.pth'
  TARGET_TYPE: gaussian
  IMAGE_SIZE:
  - 960
  - 512
  HEATMAP_SIZE:
  - 480
  - 256 # 其实用不到
  SIGMA: 6 # larger sigma
  NUM_JOINTS: 15
  NUM_CONNS: 14
  USE_GT: False
  POOLING: False

MODEL_EXTRA:
  FINAL_CONV_KERNEL: 1
  PRETRAINED_LAYERS: ['*']
  STEM_INPLANES: 64
  TAG_PER_JOINT: True
  STAGE2:
    NUM_MODULES: 1
    NUM_BRANCHES: 2
    BLOCK: BASIC
    NUM_BLOCKS:
    - 4
    - 4
    NUM_CHANNELS:
    - 32
    - 64
    FUSE_METHOD: SUM
  STAGE3:
    NUM_MODULES: 4
    NUM_BRANCHES: 3
    BLOCK: BASIC
    NUM_BLOCKS:
    - 4
    - 4
    - 4
    NUM_CHANNELS:
    - 32
    - 64
    - 128
    FUSE_METHOD: SUM
  STAGE4:
    NUM_MODULES: 3
    NUM_BRANCHES: 4
    BLOCK: BASIC
    NUM_BLOCKS:
    - 4
    - 4
    - 4
    - 4
    NUM_CHANNELS:
    - 32
    - 64
    - 128
    - 256
    FUSE_METHOD: SUM
  DECONV: # 这怎么只设置了一个，没有后续的继续操作
    NUM_DECONVS: 1
    NUM_CHANNELS:
    - 32
    KERNEL_SIZE:
    - 4
    NUM_BASIC_BLOCKS: 4
    CAT_OUTPUT:
    - True

LOSS:
  W_CHAMFER: 0.1
  NUM_STAGES: 2
  AE_LOSS_TYPE: exp
  WITH_AE_LOSS: [True, False]
  PUSH_LOSS_FACTOR: [0.001, 0.001]
  PULL_LOSS_FACTOR: [0.001, 0.001]
  WITH_HEATMAPS_LOSS: [True, True]
  HEATMAPS_LOSS_FACTOR: [1.0, 1.0]

POSE_RESNET:   # 替换成higher_HRnet
  FINAL_CONV_KERNEL: 1
  DECONV_WITH_BIAS: False
  NUM_DECONV_LAYERS: 3
  NUM_DECONV_FILTERS:
  - 256
  - 256
  - 256
  NUM_DECONV_KERNELS:
  - 4
  - 4
  - 4
  NUM_LAYERS: 50
LOSS:
  USE_TARGET_WEIGHT: true
TRAIN:
  BATCH_SIZE: 4
  SHUFFLE: true
  BEGIN_EPOCH: 0
  END_EPOCH: 40
  RESUME: True
  OPTIMIZER: adam
  LR: 0.0001

TEST:
  MODEL_FILE: 'model_best.pth.tar' #'final_state.pth.tar' 
  BATCH_SIZE: 2 # orig 6
DEBUG:
  DEBUG: true
  SAVE_HEATMAPS_GT: true
  SAVE_HEATMAPS_PRED: true
MULTI_PERSON:
  SPACE_SIZE:
    - 8000.0
    - 8000.0
    - 2000.0
  SPACE_CENTER:
    - 0.0 # 120.0
    - -500.0 # -600.0
    - 800.0
  INITIAL_CUBE_SIZE:
    - 80
    - 80
    - 20
  MAX_PEOPLE_NUM: 10
  THRESHOLD: 0.3
  VOXEL_SIZE: 
    - 100.0
    - 100.0
    - 100.0
PICT_STRUCT:
  GRID_SIZE:
    - 2000.0
    - 2000.0
    - 2000.0
  CUBE_SIZE:
    - 64
    - 64
    - 64
